const {createApp} = Vue;

createApp({
  data(){
    return{
      contacts:[
        {
          name:'Michele',
          avatar:'img/avatar_1.jpg',
          visible:true,
        },
          {
          name:'Fabio',
          avatar:'img/avatar_2.jpg',
          visible:true,
        },
          {
          name:'Samuele',
          avatar:'img/avatar_3.jpg',
          visible:true,
        },
          {
          name:'Alessandro B.',
          avatar:'img/avatar_4.jpg',
          visible:true,
        },
          {
          name:'Alessandro L.',
          avatar:'img/avatar_5.jpg',
          visible:true,
        },
          {
          name:'Claudia',
          avatar:'img/avatar_6.jpg',
          visible:true,
        },
          {
          name:'Federico',
          avatar:'img/avatar_7.jpg',
          visible:true,
        },
          {
          name:'Michele',
          avatar:'img/avatar_8.jpg',
          visible:true,
        },
      ]
    }
  }
}).mount('#app')